server:
   port: 3000
   servlet:
      context-path: /

spring:
   application:
      name: order-standalone

   datasource:
      url: jdbc:mysql://localhost:3306/demo
      username: root
      password: 123456
      hikari:
         connection-timeout: 3000