server:
   port: 3000
   servlet:
      context-path: /

spring:
   application:
      name: order-standalone

   datasource:
      url: jdbc:mysql://47.116.6.177:3306/warehouse_dev
      username: root
      password: Xiezhu.123456
      hikari:
         connection-timeout: 3000