server:
   port: 0
   servlet:
      context-path: /
   tomcat:
      max-threads: 16

spring:
   application:
      name: user
   jackson:
      default-property-inclusion: non_null
   
   cloud:
      consul:
         host: localhost
         port: 8500
         discovery:
            instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}-${random.int[10000,99999]}
            tags: version=1
   
   datasource:
      url: jdbc:mysql://localhost:3306/db_user
      username: root
      password: 123456
      hikari:
         connection-timeout: 3000

ribbon:
   ServerListRefreshInterval: 5000
   ConnectTimeout: 500
   ReadTimeout: 1000
   MaxAutoRetries: 0
   MaxAutoRetriesNextServer: 1
   OkToRetryOnAllOperations: true

management:
   endpoint:
      shutdown:
         enabled: true
      health:
         show-details: always
   endpoints:
      web:
         exposure:
            include: "*"
